name: 'run-ghidra'
description: 'Run Ghidra headless analyzer'

# TODO: Support opening existing projects
# TODO: Provide default arguments format string
# TODO: Support for importing Ghidra plugins
inputs:
  project_location:
    description: 'The directory that will contain a newly created project. Optional.'
    required: false
    default: '/tmp/projects'
  project_name:
    description: 'The name of new project to be created. Optional.'
    required: false
    default: 'project'
  import:
    description: 'Specifies one or more executables to import.'
    required: true
  log:
    description: 'Sets the location of the file that stores logging information. Optional.'
    required: false
    default: 'analysis.log'

outpus:
  log:
    description: 'The contents of the headless analyzer log'

runs:
  using: 'docker'
  image: 'Dockerfile'