name: 'run-ghidra'
description: 'Run Ghidra headless analyzer'

# TODO: Support opening existing projects
inputs:
  project_location:
    description: 'The directory that will contain a newly created project. Optional.'
    required: false
    default: 'projects'
  project_name:
    description: 'The name of new project to be created. Optional.'
    required: false
    default: 'project'
  import:
    description: 'Specifies one or more executables to import.'
    required: true
  log:
    description: 'Sets the location of the file that stores logging information. Optional.'
    required: false
    default: 'application.log'
  args:
    description: 'Specifies additional arguments for Ghidra headless analyzer. Optional.'
    required: false
  plugins:
    description: 'URLs of pre-built Ghidra plugins'
    required: false

outpus:
  log:
    description: 'The contents of the headless analyzer log'

runs:
  using: 'docker'
  image: 'Dockerfile'