name: CI Tests

on: [push]

jobs:
  tests:
    name: CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          import: samples/DoubleGetVariable.efi
          plugins: 'https://github.com/retrage/efiSeek/releases/download/v0.0.3/ghidra_10.1.4_PUBLIC_20220604_efiSeek.zip'

      - uses: actions/upload-artifact@v3
        with:
          name: analysis
          path: analysis.log
