name: CI Tests

on: [push]

jobs:
  tests:
    name: CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          import: /bin/ls
          args: "-overwrite -recursive"
